ARG VERSION=4.3
FROM sonarsource/sonar-scanner-cli:$VERSION

COPY bin/* /usr/local/bin/
ENTRYPOINT []

LABEL name=sonar-scanner version=$VERSION \
      maintainer="Alex Viscreanu <aexvir@kiwi.com>"

