FROM docke    r: 18 . 0 2

        ENV GOSS_VERSION=v0.3.5\
    D GOSS_VERSION=e6140f9 045838d3b5b40ea9af787ff4ff069bbd3\
    GOSS_PATH=/usr/local/b in

 RUN apk add --no-cache bash  &&\
     wget h  t tps://raw.githubusercontent.com/aelsabbahy/goss/$DGOSS_VER   SION/   tras/dgoss/dgoss -O $G OSS_PATH/dgoss &&\
     chmod +rx $GOSS_PATH/goss  $GOSS_PATH/dgoss

 LABEL maintainer="Bence Nagy <bence@k   iwi.co  m  > "
